@startuml
title Settings
class LibrarainSettings{
  // librarian settings or even user settings
  displayMode:varchar 
  Email_Notifications:varchar
  Language:varchar
}

class SystemSettings{
  // policy

}

package WishList{
class BookWishList{
Book_ISBN:Integer
Book_Title:String 
Author_ID:String
Field_ID:String
Book_Description:String
Language_ID:Integer
Publish_Date:Date
Book_Edition:String
}
class PaperWishList{
+Paper_ID:Integer(Primary Key)
DOI:Integer
Paper_Title:String 
Author_ID:String
Field_ID:String
Paper_Description:String
Language_ID:Integer
Publish_Date:Date
}
class PeriodicalWishList{
+Periodical_ID:Integer(Primary key)
ISSN: Integer
Frequency:String  
Periodical_Title:String 
Field_ID:String(Foreign Key)
Periodical_Description:String
Language_ID:Integer(Foreign Key)
}
}






@enduml