@startuml
title Settings
class LibrarainSettings{
  // librarian settings or even user settings
  displayMode:varchar 
  Email_Notifications:varchar
  Language:varchar
}

class SystemSettings{
  // policy

}


class BookWishList{
// to recommend new books
Book_ISBN:Integer
Book_Name:String 
Author_ID:String
Field_ID:String
Book_Description:String
Language_ID:Integer
}
class PaperWishList{
// to recommend new books
Book_ISBN:Integer
Book_Name:String 
Author_ID:String
Field_ID:String
Book_Description:String
Language_ID:Integer
}



@enduml